import {StyleSheet} from 'react-native';
import {colors} from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    padding: 24,
    backgroundColor: colors.backgroundAlt,
  },
  image: {
    width: 200,
    height: 200,
  },
  imagePlaceholder: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: colors.surfaceMuted,
  },
  title: {
    marginTop: 16,
    fontSize: 24,
    fontWeight: '800',
    textTransform: 'capitalize',
    color: colors.textPrimary,
    letterSpacing: 0.3,
  },
  offlineBanner: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: colors.border,
    color: colors.textSecondary,
    textAlign: 'center',
    fontSize: 12,
  },
  favoriteButton: {
    marginTop: 10,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 3,
  },
  favoriteButtonActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  favoriteButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  favoriteButtonTextActive: {
    color: colors.surface,
  },
  helper: {
    marginTop: 8,
    textAlign: 'center',
    color: colors.textSecondary,
  },
  typesRow: {
    flexDirection: 'row',
    marginTop: 14,
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  typeChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 2,
  },
  typeChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.surface,
    textTransform: 'capitalize',
  },
  section: {
    marginTop: 20,
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.7,
    shadowRadius: 12,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  statName: {
    width: 92,
    fontSize: 12,
    color: colors.textSecondary,
    textTransform: 'capitalize',
  },
  statBarTrack: {
    flex: 1,
    height: 10,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
    overflow: 'hidden',
  },
  statBarFill: {
    height: '100%',
    backgroundColor: colors.accent,
  },
  statValue: {
    width: 36,
    textAlign: 'right',
    fontSize: 12,
    color: colors.textPrimary,
  },
  abilitiesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  abilityChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  abilityChipText: {
    fontSize: 12,
    color: colors.textSecondary,
    textTransform: 'capitalize',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.9,
    shadowRadius: 18,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    textTransform: 'capitalize',
    marginBottom: 8,
  },
  modalText: {
    fontSize: 13,
    color: colors.textPrimary,
  },
  modalTextMuted: {
    marginTop: 8,
    fontSize: 12,
    color: colors.textSecondary,
  },
  modalButton: {
    marginTop: 12,
    alignSelf: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: colors.accent,
  },
  modalButtonText: {
    color: colors.surface,
    fontSize: 12,
    fontWeight: '700',
  },
});
